/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void testAdd() {
        App app = new App();
        assertEquals(6, app.add(3, 3));
    }

    @Test
    public void testExtractTextFromImage() {
        // Assuming you have a test image file with text "Hello World"
        String imagePath = "path/to/test/image.png"; // Replace with actual test file
        try {
            String text = App.extractTextFromImage(imagePath);
            assertTrue(text.contains("Hello World"), "OCR output should contain 'Hello World'");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
